# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreatingProject_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreatingProject(object):
    def setupUi(self, CreatingProject):
        CreatingProject.setObjectName("CreatingProject")
        CreatingProject.resize(401, 252)
        self.project_name = QtWidgets.QLineEdit(CreatingProject)
        self.project_name.setGeometry(QtCore.QRect(100, 10, 291, 31))
        self.project_name.setObjectName("project_name")
        self.frame_width = QtWidgets.QSpinBox(CreatingProject)
        self.frame_width.setGeometry(QtCore.QRect(90, 100, 71, 31))
        self.frame_width.setMaximum(4500)
        self.frame_width.setObjectName("frame_width")
        self.label = QtWidgets.QLabel(CreatingProject)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(CreatingProject)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 51, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(CreatingProject)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 41, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(CreatingProject)
        self.label_4.setGeometry(QtCore.QRect(190, 100, 41, 31))
        self.label_4.setObjectName("label_4")
        self.frame_height = QtWidgets.QSpinBox(CreatingProject)
        self.frame_height.setGeometry(QtCore.QRect(250, 100, 71, 31))
        self.frame_height.setMaximum(4500)
        self.frame_height.setObjectName("frame_height")
        self.pushButton = QtWidgets.QPushButton(CreatingProject)
        self.pushButton.setGeometry(QtCore.QRect(50, 210, 141, 31))
        self.pushButton.setObjectName("pushButton")
        self.cancel = QtWidgets.QPushButton(CreatingProject)
        self.cancel.setGeometry(QtCore.QRect(210, 210, 141, 31))
        self.cancel.setObjectName("cancel")
        self.label_5 = QtWidgets.QLabel(CreatingProject)
        self.label_5.setGeometry(QtCore.QRect(30, 150, 81, 31))
        self.label_5.setObjectName("label_5")
        self.default_color = QtWidgets.QPushButton(CreatingProject)
        self.default_color.setGeometry(QtCore.QRect(120, 150, 61, 31))
        self.default_color.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.default_color.setText("")
        self.default_color.setObjectName("default_color")

        self.retranslateUi(CreatingProject)
        QtCore.QMetaObject.connectSlotsByName(CreatingProject)

    def retranslateUi(self, CreatingProject):
        _translate = QtCore.QCoreApplication.translate
        CreatingProject.setWindowTitle(_translate("CreatingProject", "Creating Project"))
        self.label.setText(_translate("CreatingProject", "Project name"))
        self.label_2.setText(_translate("CreatingProject", "Frame:"))
        self.label_3.setText(_translate("CreatingProject", "Width:"))
        self.label_4.setText(_translate("CreatingProject", "Height:"))
        self.pushButton.setText(_translate("CreatingProject", "Create project"))
        self.cancel.setText(_translate("CreatingProject", "Cancel"))
        self.label_5.setText(_translate("CreatingProject", "Default color:"))
