# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpeningProject_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_OpenProject(object):
    def setupUi(self, OpenProject):
        OpenProject.setObjectName("OpenProject")
        OpenProject.resize(400, 112)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OpenProject.sizePolicy().hasHeightForWidth())
        OpenProject.setSizePolicy(sizePolicy)
        self.projects_to_open = QtWidgets.QComboBox(OpenProject)
        self.projects_to_open.setGeometry(QtCore.QRect(20, 20, 361, 31))
        self.projects_to_open.setObjectName("projects_to_open")
        self.open = QtWidgets.QPushButton(OpenProject)
        self.open.setGeometry(QtCore.QRect(90, 60, 93, 41))
        self.open.setObjectName("open")
        self.cancel = QtWidgets.QPushButton(OpenProject)
        self.cancel.setGeometry(QtCore.QRect(210, 60, 93, 41))
        self.cancel.setObjectName("cancel")

        self.retranslateUi(OpenProject)
        QtCore.QMetaObject.connectSlotsByName(OpenProject)

    def retranslateUi(self, OpenProject):
        _translate = QtCore.QCoreApplication.translate
        OpenProject.setWindowTitle(_translate("OpenProject", "Opening Project"))
        self.open.setText(_translate("OpenProject", "Open"))
        self.cancel.setText(_translate("OpenProject", "Cancel"))
