# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tools_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UI_Tools(object):
    def setupUi(self, UI_Tools):
        UI_Tools.setObjectName("UI_Tools")
        UI_Tools.resize(291, 162)
        self.lmbBtn = QtWidgets.QPushButton(UI_Tools)
        self.lmbBtn.setGeometry(QtCore.QRect(80, 30, 51, 51))
        self.lmbBtn.setText("")
        self.lmbBtn.setObjectName("lmbBtn")
        self.rmbBtn = QtWidgets.QPushButton(UI_Tools)
        self.rmbBtn.setGeometry(QtCore.QRect(160, 30, 51, 51))
        self.rmbBtn.setText("")
        self.rmbBtn.setObjectName("rmbBtn")
        self.swapBtn = QtWidgets.QPushButton(UI_Tools)
        self.swapBtn.setGeometry(QtCore.QRect(130, 40, 31, 31))
        self.swapBtn.setObjectName("swapBtn")
        self.isFillBtn = QtWidgets.QRadioButton(UI_Tools)
        self.isFillBtn.setGeometry(QtCore.QRect(20, 40, 41, 31))
        self.isFillBtn.setIconSize(QtCore.QSize(20, 20))
        self.isFillBtn.setObjectName("isFillBtn")
        self.label = QtWidgets.QLabel(UI_Tools)
        self.label.setGeometry(QtCore.QRect(80, 10, 51, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(UI_Tools)
        self.label_2.setGeometry(QtCore.QRect(160, 10, 51, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(UI_Tools)
        self.label_5.setGeometry(QtCore.QRect(-20, 100, 271, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lineSize = QtWidgets.QSpinBox(UI_Tools)
        self.lineSize.setGeometry(QtCore.QRect(160, 100, 51, 31))
        self.lineSize.setObjectName("lineSize")
        self.lineThick = QtWidgets.QSlider(UI_Tools)
        self.lineThick.setGeometry(QtCore.QRect(10, 130, 271, 22))
        self.lineThick.setOrientation(QtCore.Qt.Horizontal)
        self.lineThick.setObjectName("lineThick")

        self.retranslateUi(UI_Tools)
        QtCore.QMetaObject.connectSlotsByName(UI_Tools)

    def retranslateUi(self, UI_Tools):
        _translate = QtCore.QCoreApplication.translate
        UI_Tools.setWindowTitle(_translate("UI_Tools", "Tools"))
        self.swapBtn.setText(_translate("UI_Tools", "<->"))
        self.isFillBtn.setText(_translate("UI_Tools", "Fill"))
        self.label.setText(_translate("UI_Tools", "LMB"))
        self.label_2.setText(_translate("UI_Tools", "RMB"))
        self.label_5.setText(_translate("UI_Tools", "Line thickness"))
